name: Docker-CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Build nginx
        run: docker build -t custom-nginx:latest .

      - name: Build and start containers
        run: docker run -d --name my-nginx -p 8090:80 custom-nginx

  logs:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Check number of containers
        run: docker ps

      - name: Check Docker logs 
        run: docker logs 8afaf9fca1ee

  deploy:
    needs: logs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Check curl deployment 
        run: curl localhost:8090

